import type { Cardinality, Diagram, Table } from "@/lib/types"

export type Dialect = "postgres" | "mysql" | "sqlite"

const TYPE_MAP: Record<Dialect, Record<string, string>> = {
  postgres: {
    string: "text",
    int: "integer",
    float: "double precision",
    datetime: "timestamptz",
    bool: "boolean",
  },
  mysql: {
    uuid: "char(36)",
    string: "varchar(255)",
    bool: "tinyint(1)",
    boolean: "tinyint(1)",
    timestamptz: "timestamp",
    jsonb: "json",
    bytea: "blob",
    serial: "int auto_increment",
  },
  sqlite: {
    uuid: "text",
    string: "text",
    varchar: "text",
    int: "integer",
    bigint: "integer",
    smallint: "integer",
    serial: "integer",
    bool: "integer",
    boolean: "integer",
    float: "real",
    decimal: "numeric",
    jsonb: "text",
    json: "text",
    timestamptz: "text",
    timestamp: "text",
    bytea: "blob",
  },
}

const quote = (dialect: Dialect, ident: string) => {
  const safe = ident.trim().replace(/\s+/g, "_")
  return dialect === "mysql" ? `\`${safe}\`` : `"${safe}"`
}

const mapType = (dialect: Dialect, type: string) => {
  const key = type.trim().toLowerCase()
  return TYPE_MAP[dialect][key] ?? type.trim()
}

/** A cardinality that permits more than one row marks the "many" side of a relationship. */
const isMany = (c: Cardinality) => c === "one-or-more" || c === "zero-or-more"
const isOptional = (c: Cardinality) => c === "zero-or-one" || c === "zero-or-more"

interface ForeignKey {
  childTableId: string
  childColumn: string
  parentTable: string
  parentColumn: string
  optional: boolean
}

function deriveForeignKeys(diagram: Diagram) {
  const byId = new Map(diagram.tables.map((t) => [t.id, t]))
  const keys: ForeignKey[] = []
  const warnings: string[] = []

  for (const rel of diagram.relationships) {
    const source = byId.get(rel.sourceTableId)
    const target = byId.get(rel.targetTableId)
    if (!source || !target) continue

    // The "many" side owns the foreign key; ties resolve to the target table.
    const childIsTarget = isMany(rel.targetCardinality) || !isMany(rel.sourceCardinality)
    const child: Table = childIsTarget ? target : source
    const parent: Table = childIsTarget ? source : target
    const parentKey = parent.columns.find((c) => c.pk)
    if (!parentKey) {
      warnings.push(`-- ${parent.name} has no primary key; skipped FK from ${child.name}`)
      continue
    }

    const explicit = childIsTarget ? rel.targetColumnId : rel.sourceColumnId
    const childColumn =
      child.columns.find((c) => c.id === explicit) ??
      child.columns.find((c) => c.fk && c.name.toLowerCase().includes(parent.name.toLowerCase())) ??
      child.columns.find((c) => c.name.toLowerCase() === `${parent.name.toLowerCase()}_id`)

    if (!childColumn) {
      warnings.push(
        `-- TODO: ${child.name} needs a foreign key column referencing ${parent.name}(${parentKey.name})`,
      )
      continue
    }

    keys.push({
      childTableId: child.id,
      childColumn: childColumn.name,
      parentTable: parent.name,
      parentColumn: parentKey.name,
      optional: isOptional(childIsTarget ? rel.sourceCardinality : rel.targetCardinality),
    })
  }

  return { keys, warnings }
}

export function toSql(diagram: Diagram, dialect: Dialect = "postgres"): string {
  const { keys, warnings } = deriveForeignKeys(diagram)
  const out: string[] = [`-- ${diagram.name}`, "-- Generated by Cardinal", ""]

  for (const table of diagram.tables) {
    const body: string[] = []
    for (const column of table.columns) {
      const bits = [quote(dialect, column.name), mapType(dialect, column.type)]
      if (!column.nullable || column.pk) bits.push("NOT NULL")
      if (column.uk && !column.pk) bits.push("UNIQUE")
      if (column.defaultValue) bits.push(`DEFAULT ${column.defaultValue}`)
      body.push(`  ${bits.join(" ")}`)
    }

    const pks = table.columns.filter((c) => c.pk)
    if (pks.length) body.push(`  PRIMARY KEY (${pks.map((c) => quote(dialect, c.name)).join(", ")})`)

    // SQLite cannot add constraints after the fact, so inline them here.
    if (dialect === "sqlite") {
      for (const fk of keys.filter((k) => k.childTableId === table.id)) {
        body.push(
          `  FOREIGN KEY (${quote(dialect, fk.childColumn)}) REFERENCES ${quote(dialect, fk.parentTable)} (${quote(dialect, fk.parentColumn)}) ON DELETE ${fk.optional ? "SET NULL" : "CASCADE"}`,
        )
      }
    }

    if (table.comment) out.push(`-- ${table.comment}`)
    out.push(`CREATE TABLE ${quote(dialect, table.name)} (`, body.join(",\n"), ");", "")
  }

  if (dialect !== "sqlite" && keys.length) {
    out.push("-- Foreign keys")
    for (const fk of keys) {
      const child = diagram.tables.find((t) => t.id === fk.childTableId)
      if (!child) continue
      out.push(
        `ALTER TABLE ${quote(dialect, child.name)} ADD CONSTRAINT ${quote(dialect, `fk_${child.name}_${fk.childColumn}`.toLowerCase())}`,
        `  FOREIGN KEY (${quote(dialect, fk.childColumn)}) REFERENCES ${quote(dialect, fk.parentTable)} (${quote(dialect, fk.parentColumn)}) ON DELETE ${fk.optional ? "SET NULL" : "CASCADE"};`,
      )
    }
    out.push("")
  }

  if (warnings.length) out.push(...warnings, "")
  return out.join("\n")
}
